### ISSUE TITLE
[Feat] add controller about member entity

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#14]
## Description
> add controller class about member entity and test it
## TODO
- [x] register member api
- [x] modify member info api 
- [x] get member info api

**Comment by H4nnhoi** [comment]
## ISSUE
Q. controller test 시 발생하는 401, 403 에러는 어떻게 처리해야하는가

A. 해당 에러는 스프링이 테스트 코드에서 spring security를 최소한의 세팅으로 해두기 때문에 발생하는 에러다. 따라서 별도의 세팅이 필요한데 
1. @AutoConfigureMockMvc(addFilters = false)
2. @WithMockUser추가

1번의 설정으로 별도의 csrf 검증 없이 테스트가 가능하다.

1번만으로도 오류를 피할 수 있지만 나중에 token사용 시 오류가 발생할 것이다. token을 통해 member의 정보를 가져오는 필터를 거치지 않기 때문이다. 그렇기에 2번 설정이 필요하다.(지금은 아님) 나중에 인증 정보를 가져오는 과정에서 해당 설정을 통해 Authentication = null의 결과를 해결할 수 있다.
