### ISSUE TITLE
[Feat] add global response form (using controllerAdvice)

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#16]
## Description
> Using controllerAdvice, add global response form
## TODO
- [x] make apiResponseDto
- [x] add controlleradvice and process all about rest api
- [x] set custom exception
- [x] process all about exception using controlleradvice

**Comment by H4nnhoi** [comment]
# ISSUE
GeneralException에 
~~~java
@Override
public String getMessage() {
    return code.getReason().getMessage();
}
~~~
을 추가해줬다. 이유는 테스트 코드에서 hasMessage()메서드를 사용하는데, 우리가 가져올 수 있는 message는 handler의 reason의 basecode가 가지는 필드인 message인 것이다. 이설정을 해주면 runtimeException의 메세지에도 직접적으로 넣어줄 수 있다. 

실제 기능에서는 거의 필요 없지만 테스트 코드를 위함이라고 생각하면 된다.
