### ISSUE TITLE
[Feat] make promotion controller and test it

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#18]
## Description
> make promotion controller about CRUD, and test it
## TODO
- [x] add create promotion api(POST)
- [x] add modify promotion api(PUT)
- [x] add read promotion api(GET)
- [x] add read promotion list api(GET)
- [x] add delete promotion api(DELETE)
- [x] refactor promotion's music entity relation setting
- [x] test all
