### ISSUE TITLE
[Feat/35] ticket

### ISSUE THREAD

**Issue by k168ww** [playQR/playQR.back#35]
## Description
> Modify the number of user tickets and name

## TODO
- [x] 유저 티켓 인원 수 및 성명 수정 → 게스트 정보 수정
- [x] 프로모션 작성자 티켓 발급 허용 → 티켓 생성 & 게스트 isTicketIssued 변경
- [x] 작성자 티켓 신청 목록 조회
- [x] 예매 신청 철회 → 게스트 삭제

**Comment by H4nnhoi** [comment]
# Feedback
## service 분리 (Command & Query)
package 구조
|-service
|-----guest
|--------GuestCommandService
|--------GuestCommandServiceImpl
|--------GuestQueryService
|--------GuestQueryServiceImpl
|-----ticket
|---------TicketCommandService
|---------TicketCommandServiceImpl
|---------TicketQueryService
|---------TicketQueryServiceImpl

## exception 처리(GeneralException상속 예외 클래스 생성 후 throw)
example
~~~java
Promotion updatePromotion = promotionRepository.findById(promotionId)
                .orElseThrow(() -> new PromotionHandler(ErrorStatus.PROMOTION_NOT_FOUND));
~~~
## AuthUser로 인한 member엔티티 사용
대체로 member관련 엔티티로 다른 데이터를 생성, 수정, 삭제 시에 인자로 memberid 대신 member를 사용하시는 게 더 좋을겁니다. controller에서  액세스 토큰이 있으면 @AuthUser로 member엔티티를 반환하게 됩니다. 그래서 해당 값을 인자로 사용하실 수 있어서 굳이 재차 memberRepository.findById()메서드를 사용하실 필요가 없습니다.
