### ISSUE TITLE
[Feat] register manager in promotion

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#39]
## Description
> create manager entity & give it to authorization
## TODO
- [ ] create manager entity
- [ ] register
- [ ] issue ticket(auth)
- [ ] rollback issuing
- [ ] get guest list
- [ ] get out of promotion
- [ ] test service code
- [ ] make api
