### ISSUE TITLE
[Test] test code of guest & ticket

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#42]
## Description
> test code of guest. it will be work later at feat/#35 branch
## TODO
- [x] create Guest client
- [x] update Guest from client
- [x] issue Ticket
- [x] check status of Ticket(isEntranced)
- [x] cancel Ticket from host
