### ISSUE TITLE
[Refactor] security request from front-end

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#48]
## Description
> security request from front-end
## TODO
- [x] reissue token api
- [x] get member info when get access
- [x] return with expire time
- [x] remove server login
