### ISSUE TITLE
[Refactor] edit promotion dto field

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#51]
## Description
> from front-end request, edit promotion dto field
## TODO
- [x] remove option entity 
- [x] add date, time, location, bank, account, accountHolder, and refund_info in promotion entity
- [x] unify search & get promotion
