### ISSUE TITLE
[Feat] Manager

### ISSUE THREAD

**Issue by k168ww** [playQR/playQR.back#54]
## Description
> Manager function implementation
## TODO
- [ ] 작성자 board manager 등록하기
- [ ] manager 게스트 명단 조회하기
- [ ] manager 게스트에게 티켓 발급하기
- [ ] board의 manager 목록 조회
- [ ] 작성자 manager 지우기
