### ISSUE TITLE
[Refactor] request from frontend

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#56]
## Description
> need to refactor for frontend
## TODO
- [x] add api of get my promotion
- [x] add api of get my promotion + ticket id
- [x] error security config(need to permit get paging comment)
- [x] add field of comment id and total comment in paging comment api
