### ISSUE TITLE
[Refactor] delete promotion & member entity

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#59]
## Description
> edit deleting parent entity with relations
> and edit entity structure of music and promotion
## TODO
- [x] edit deleting promotion
- [x] edit deleting member
- [x] test code
- [x] remove entity of promotionMusic
