### ISSUE TITLE
[Refactor] add error status in swagger

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#60]
## Description
> add error status in swagger
## TODO
- [x] create enum for default errorstatus
- [x] edit swagger config
- [x] setting errorstatus each api
