### ISSUE TITLE
[Feat] add api

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#64]
## Description
> add missing api
## TODO
- [x] get promotion as guest
- [x] edit business code of guest(add validation when create or entrance guest)
- [x] get my comments
- [x] edit search promotion api(descending)
- [x] count reservation
- [x] add like field in get promotion
