### ISSUE TITLE
[Refactor] get nickname from kakao

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#65]
## Description
> get nickname from kakao and put in name
## TODO
- [x] get nickname from kakao
- [x] remove automatically generating nickname
- [x] convert response of name
