### ISSUE TITLE
[Feat] create status of guest

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#74]
## Description
> need to check guest(BEFORE_CONFIRMATION, AFTER_CONFIRMATION, CHECKED_IN)
## TODO
- [x] create status enum
- [x] get status api
- [x] add api of approve reservation
- [x] add validation in entrance
