### ISSUE TITLE
[Feat] add necessary api 

### ISSUE THREAD

**Issue by H4nnhoi** [playQR/playQR.back#85]
## Description
> add necessary api
## TODO
- [x] get checking reservation api
- [x] get list of my_like_promotion api
- [x] add enum of bank type
